version: "3.3"

services:
  db:
    image: postgres:13
    env_file:
      - .env
    container_name: db_postgres_container
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5556:5432"

  backend:
    build:
      context: .
      dockerfile: ./src/django_project/Dockerfile
    container_name: core
    hostname: core
    user: root
    environment:
      DEBUG: 'true'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
